=== trentcowden/tov/data/schemas/books.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "items": {
    "additionalProperties": false,
    "properties": {
      "bookId": {
        "$ref": "./ids.json#/properties/bookId"
      },
      "chapters": {
        "items": {
          "type": "string"
        }
      },
      "englishDivision": {
        "$ref": "./ids.json#/properties/englishDivision"
      },
      "hebrewDivision": {
        "$ref": "./ids.json#/properties/hebrewDivision"
      },
      "hebrewOrder": {
        "type": [
          "number",
          "null"
        ]
      },
      "name": {
        "type": "string"
      },
      "order": {
        "type": "number"
      },
      "testament": {
        "$ref": "./ids.json#/properties/testament"
      }
    },
    "required": [
      "bookId",
      "chapters",
      "englishDivision",
      "hebrewDivision",
      "hebrewOrder",
      "name",
      "order",
      "testament"
    ]
  },
  "type": "array"
}

=== trentcowden/tov/data/books.json
[
  {
    "bookId": "GEN",
    "chapters": [
      "GEN.1",
      "GEN.2",
      "GEN.3",
      "GEN.4",
      "GEN.5",
      "GEN.6",
      "GEN.7",
      "GEN.8",
      "GEN.9",
      "GEN.10",
      "GEN.11",
      "GEN.12",
      "GEN.13",
      "GEN.14",
      "GEN.15",
      "GEN.16",
      "GEN.17",
      "GEN.18",
      "GEN.19",
      "GEN.20",
      "GEN.21",
      "GEN.22",
      "GEN.23",
      "GEN.24",
      "GEN.25",
      "GEN.26",
      "GEN.27",
      "GEN.28",
      "GEN.29",
      "GEN.30",
      "GEN.31",
      "GEN.32",
      "GEN.33",
      "GEN.34",
      "GEN.35",
      "GEN.36",
      "GEN.37",
      "GEN.38",
      "GEN.39",
      "GEN.40",
      "GEN.41",
      "GEN.42",
      "GEN.43",
      "GEN.44",
      "GEN.45",
      "GEN.46",
      "GEN.47",
      "GEN.48",
      "GEN.49",
      "GEN.50"
    ],
    "englishDivision": "pentateuch",
    "hebrewDivision": "torah",
    "hebrewOrder": 1,
    "name": "Genesis",
    "order": 1,
    "testament": "old"
  },
  {
    "bookId": "EXO",
    "chapters": [
      "EXO.1",
      "EXO.2",
      "EXO.3",
      "EXO.4",
      "EXO.5",
      "EXO.6",
      "EXO.7",
      "EXO.8",
      "EXO.9",
      "EXO.10",
      "EXO.11",
      "EXO.12",
      "EXO.13",
      "EXO.14",
      "EXO.15",
      "EXO.16",
      "EXO.17",
      "EXO.18",
      "EXO.19",
      "EXO.20",
      "EXO.21",
      "EXO.22",
      "EXO.23",
      "EXO.24",
      "EXO.25",
      "EXO.26",
      "EXO.27",
      "EXO.28",
      "EXO.29",
      "EXO.30",
      "EXO.31",
      "EXO.32",
      "EXO.33",
      "EXO.34",
      "EXO.35",
      "EXO.36",
      "EXO.37",
      "EXO.38",
      "EXO.39",
      "EXO.40"
    ],
    "englishDivision": "pentateuch",
    "hebrewDivision": "torah",
    "hebrewOrder": 2,
    "name": "Exodus",
    "order": 2,
    "testament": "old"
  },
  {
    "bookId": "LEV",
    "chapters": [
      "LEV.1",
      "LEV.2",
      "LEV.3",
      "LEV.4",
      "LEV.5",
      "LEV.6",
      "LEV.7",
      "LEV.8",
      "LEV.9",
      "LEV.10",
      "LEV.11",
      "LEV.12",
      "LEV.13",
      "LEV.14",
      "LEV.15",
      "LEV.16",
      "LEV.17",
      "LEV.18",
      "LEV.19",
      "LEV.20",
      "LEV.21",
      "LEV.22",
      "LEV.23",
      "LEV.24",
      "LEV.25",
      "LEV.26",
      "LEV.27"
    ],
    "englishDivision": "pentateuch",
    "hebrewDivision": "torah",
    "hebrewOrder": 3,
    "name": "Leviticus",
    "order": 3,
    "testament": "old"
  },
  {
    "bookId": "NUM",
    "chapters": [
      "NUM.1",
      "NUM.2",
      "NUM.3",
      "NUM.4",
      "NUM.5",
      "NUM.6",
      "NUM.7",
      "NUM.8",
      "NUM.9",
      "NUM.10",
      "NUM.11",
      "NUM.12",
      "NUM.13",
      "NUM.14",
      "NUM.15",
      "NUM.16",
      "NUM.17",
      "NUM.18",
      "NUM.19",
      "NUM.20",
      "NUM.21",
      "NUM.22",
      "NUM.23",
      "NUM.24",
      "NUM.25",
      "NUM.26",
      "NUM.27",
      "NUM.28",
      "NUM.29",
      "NUM.30",
      "NUM.31",
      "NUM.32",
      "NUM.33",
      "NUM.34",
      "NUM.35",
      "NUM.36"
    ],
    "englishDivision": "pentateuch",
    "hebrewDivision": "torah",
    "hebrewOrder": 4,
    "name": "Numbers",
    "order": 4,
    "testament": "old"
  },
  {
    "bookId": "DEU",
    "chapters": [
      "DEU.1",
      "DEU.2",
      "DEU.3",
      "DEU.4",
      "DEU.5",
      "DEU.6",
      "DEU.7",
      "DEU.8",
      "DEU.9",
      "DEU.10",
      "DEU.11",
      "DEU.12",
      "DEU.13",
      "DEU.14",
      "DEU.15",
      "DEU.16",
      "DEU.17",
      "DEU.18",
      "DEU.19",
      "DEU.20",
      "DEU.21",
      "DEU.22",
      "DEU.23",
      "DEU.24",
      "DEU.25",
      "DEU.26",
      "DEU.27",
      "DEU.28",
      "DEU.29",
      "DEU.30",
      "DEU.31",
      "DEU.32",
      "DEU.33",
      "DEU.34"
    ],
    "englishDivision": "pentateuch",
    "hebrewDivision": "torah",
    "hebrewOrder": 5,
    "name": "Deuteronomy",
    "order": 5,
    "testament": "old"
  },
  {
    "bookId": "JOS",
    "chapters": [
      "JOS.1",
      "JOS.2",
      "JOS.3",
      "JOS.4",
      "JOS.5",
      "JOS.6",
      "JOS.7",
      "JOS.8",
      "JOS.9",
      "JOS.10",
      "JOS.11",
      "JOS.12",
      "JOS.13",
      "JOS.14",
      "JOS.15",
      "JOS.16",
      "JOS.17",
      "JOS.18",
      "JOS.19",
      "JOS.20",
      "JOS.21",
      "JOS.22",
      "JOS.23",
      "JOS.24"
    ],
    "englishDivision": "historical",
    "hebrewDivision": "nevi'im",
    "hebrewOrder": 6,
    "name": "Joshua",
    "order": 6,
    "testament": "old"
  },
  {
    "bookId": "JDG",
    "chapters": [
      "JDG.1",
      "JDG.2",
      "JDG.3",
      "JDG.4",
      "JDG.5",
      "JDG.6",
      "JDG.7",
      "JDG.8",
      "JDG.9",
      "JDG.10",
      "JDG.11",
      "JDG.12",
      "JDG.13",
      "JDG.14",
      "JDG.15",
      "JDG.16",
      "JDG.17",
      "JDG.18",
      "JDG.19",
      "JDG.20",
      "JDG.21"
    ],
    "englishDivision": "historical",
    "hebrewDivision": "nevi'im",
    "hebrewOrder": 7,
    "name": "Judges",
    "order": 7,
    "testament": "old"
  },
  {
    "bookId": "RUT",
    "chapters": ["RUT.1", "RUT.2", "RUT.3", "RUT.4"],
    "englishDivision": "historical",
    "hebrewDivision": "ketuvim",
    "hebrewOrder": 31,
    "name": "Ruth",
    "order": 8,
    "testament": "old"
  },
  {
    "bookId": "1SA",
    "chapters": [
      "1SA.1",
      "1SA.2",
      "1SA.3",
      "1SA.4",
      "1SA.5",
      "1SA.6",
      "1SA.7",
      "1SA.8",
      "1SA.9",
      "1SA.10",
      "1SA.11",
      "1SA.12",
      "1SA.13",
      "1SA.14",
      "1SA.15",
      "1SA.16",
      "1SA.17",
      "1SA.18",
      "1SA.19",
      "1SA.20",
      "1SA.21",
      "1SA.22",
      "1SA.23",
      "1SA.24",
      "1SA.25",
      "1SA.26",
      "1SA.27",
      "1SA.28",
      "1SA.29",
      "1SA.30",
      "1SA.31"
    ],
    "englishDivision": "historical",
    "hebrewDivision": "nevi'im",
    "hebrewOrder": 8,
    "name": "1 Samuel",
    "order": 9,
    "testament": "old"
  },
  {
    "bookId": "2SA",
    "chapters": [
      "2SA.1",
      "2SA.2",
      "2SA.3",
      "2SA.4",
      "2SA.5",
      "2SA.6",
      "2SA.7",
      "2SA.8",
      "2SA.9",
      "2SA.10",
      "2SA.11",
      "2SA.12",
      "2SA.13",
      "2SA.14",
      "2SA.15",
      "2SA.16",
      "2SA.17",
      "2SA.18",
      "2SA.19",
      "2SA.20",
      "2SA.21",
      "2SA.22",
      "2SA.23",
      "2SA.24"
    ],
    "englishDivision": "historical",
    "hebrewDivision": "nevi'im",
    "hebrewOrder": 9,
    "name": "2 Samuel",
    "order": 10,
    "testament": "old"
  },
  {
    "bookId": "1KI",
    "chapters": [
      "1KI.1",
      "1KI.2",
      "1KI.3",
      "1KI.4",
      "1KI.5",
      "1KI.6",
      "1KI.7",
      "1KI.8",
      "1KI.9",
      "1KI.10",
      "1KI.11",
      "1KI.12",
      "1KI.13",
      "1KI.14",
      "1KI.15",
      "1KI.16",
      "1KI.17",
      "1KI.18",
      "1KI.19",
      "1KI.20",
      "1KI.21",
      "1KI.22"
    ],
    "englishDivision": "historical",
    "hebrewDivision": "nevi'im",
    "hebrewOrder": 10,
    "name": "1 Kings",
    "order": 11,
    "testament": "old"
  },
  {
    "bookId": "2KI",
    "chapters": [
      "2KI.1",
      "2KI.2",
      "2KI.3",
      "2KI.4",
      "2KI.5",
      "2KI.6",
      "2KI.7",
      "2KI.8",
      "2KI.9",
      "2KI.10",
      "2KI.11",
      "2KI.12",
      "2KI.13",
      "2KI.14",
      "2KI.15",
      "2KI.16",
      "2KI.17",
      "2KI.18",
      "2KI.19",
      "2KI.20",
      "2KI.21",
      "2KI.22",
      "2KI.23",
      "2KI.24",
      "2KI.25"
    ],
    "englishDivision": "historical",
    "hebrewDivision": "nevi'im",
    "hebrewOrder": 11,
    "name": "2 Kings",
    "order": 12,
    "testament": "old"
  },
  {
    "bookId": "1CH",
    "chapters": [
      "1CH.1",
      "1CH.2",
      "1CH.3",
      "1CH.4",
      "1CH.5",
      "1CH.6",
      "1CH.7",
      "1CH.8",
      "1CH.9",
      "1CH.10",
      "1CH.11",
      "1CH.12",
      "1CH.13",
      "1CH.14",
      "1CH.15",
      "1CH.16",
      "1CH.17",
      "1CH.18",
      "1CH.19",
      "1CH.20",
      "1CH.21",
      "1CH.22",
      "1CH.23",
      "1CH.24",
      "1CH.25",
      "1CH.26",
      "1CH.27",
      "1CH.28",
      "1CH.29"
    ],
    "englishDivision": "historical",
    "hebrewDivision": "ketuvim",
    "hebrewOrder": 38,
    "name": "1 Chronicles",
    "order": 13,
    "testament": "old"
  },
  {
    "bookId": "2CH",
    "chapters": [
      "2CH.1",
      "2CH.2",
      "2CH.3",
      "2CH.4",
      "2CH.5",
      "2CH.6",
      "2CH.7",
      "2CH.8",
      "2CH.9",
      "2CH.10",
      "2CH.11",
      "2CH.12",
      "2CH.13",
      "2CH.14",
      "2CH.15",
      "2CH.16",
      "2CH.17",
      "2CH.18",
      "2CH.19",
      "2CH.20",
      "2CH.21",
      "2CH.22",
      "2CH.23",
      "2CH.24",
      "2CH.25",
      "2CH.26",
      "2CH.27",
      "2CH.28",
      "2CH.29",
      "2CH.30",
      "2CH.31",
      "2CH.32",
      "2CH.33",
      "2CH.34",
      "2CH.35",
      "2CH.36"
    ],
    "englishDivision": "historical",
    "hebrewDivision": "ketuvim",
    "hebrewOrder": 39,
    "name": "2 Chronicles",
    "order": 14,
    "testament": "old"
  },
  {
    "bookId": "EZR",
    "chapters": [
      "EZR.1",
      "EZR.2",
      "EZR.3",
      "EZR.4",
      "EZR.5",
      "EZR.6",
      "EZR.7",
      "EZR.8",
      "EZR.9",
      "EZR.10"
    ],
    "englishDivision": "historical",
    "hebrewDivision": "ketuvim",
    "hebrewOrder": 36,
    "name": "Ezra",
    "order": 15,
    "testament": "old"
  },
  {
    "bookId": "NEH",
    "chapters": [
      "NEH.1",
      "NEH.2",
      "NEH.3",
      "NEH.4",
      "NEH.5",
      "NEH.6",
      "NEH.7",
      "NEH.8",
      "NEH.9",
      "NEH.10",
      "NEH.11",
      "NEH.12",
      "NEH.13"
    ],
    "englishDivision": "historical",
    "hebrewDivision": "ketuvim",
    "hebrewOrder": 37,
    "name": "Nehemiah",
    "order": 16,
    "testament": "old"
  },
  {
